### ISSUE TITLE
A non-existant config file should not be an error

### ISSUE THREAD

**Issue by tevansuk** [sherifabdlnaby/configuro#2]
It should be optional to actually have a config file - you might be specifying everything as environment variables

https://github.com/sherifabdlnaby/configuro/blob/a580de8cd5c11380db8453e78212578ca2bad673/load.go#L21

viper has example code on how to ignore it:

https://github.com/spf13/viper#reading-config-files

**Comment by viettd** [comment]
IMHO, non existent file should be considered an error when `config.configFileLoad` is `true`.

**Comment by tevansuk** [comment]
Consider a program that is distributed. How do you want to configure this
program? That's not really up to the distributor. Some users may put in
place a config file. Some may 12factor it. Some might do both.

It's common enough that viper, which configuro is a thin wrapper around,
has specific code to detect that type of error and ignore it. Common enough
that they put example code in the overview on how to do it.

**Comment by sherifabdlnaby** [comment]
I see, I can see this option makes it easier to configure docker images where base images doesn't need a config file by default but containers optionally load files on runtime.

However I think this needs to **optional**  and **be explicitly set** when constructing Configuro struct via option.
